[package]
name = "misato"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
handlebars = "4.1.2"
toml = "0.5.8"
rsass = "0.22.2"